server:
    port: 7788
    ssl:
      key-store: classpath:firstapp.p12
      key-store-password: firstapppass
      key-password: firstapppass     
security:
    require-ssl: true
logging:
  level:
    root: INFO         
    org:
      springframework:
        security: INFO 
        web: INFO